name: Linting
on: 
  [push]

jobs:
  lint:
    name: Run linting
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install
        working-directory: ./source/client/angular
      - name: Lint
        run: npm run lint
        working-directory: ./source/client/angular
