name: Node.js CI

on: 
  pull_request:
    branches: 
      - master
      - releases/*

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - working-directory: ./source/client
    - run: npm install
    - run: npm lint
    
