name: Linting
on: 
  [push]

jobs:
  lint:
    name: Run linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Hello world
        run: echo 'Hello World'

      - name: Install dependencies
        run: npm install
        working-directory: ../source/client/angular
      - name: Lint
        run: npm run lint
        working-directory: ../source/client/angular
