name: Node.js CI

on: 
  pull_request:
    branches: 
      - master
      - releases/*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - working-directory: ./source/client
    - run: npm install
    - run: npm lint
    
