name: Node.js CI

on: 
  [push]

jobs:
  lint:
    name: Run linting
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo 'Hello World'
      - name: Install dependencies
        working-directory: ./source/client/angular
        run: npm install
        
