name: Node.js CI

on: 
  pull_request:
    branches: 
      - master
      - releases/*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
      - run: npm install
      - run: npm lint
      - working-directory: ./source/client
